/**
 * Allowed lifecycle states for a task.
 * Valid values are limited to `todo`, `in-progress`, or `done`.
 */
export type TaskStatus = 'todo' | 'in-progress' | 'done';

/**
 * Persisted task record returned by the API.
 */
export interface Task {
  /**
   * Unique task identifier.
   * Expected to be a UUID string generated by the API.
   */
  id: string;

  /**
   * Short task title.
   * Valid range: non-empty trimmed string with at least 1 character.
   */
  title: string;

  /**
   * Detailed task description.
   * Valid range: non-empty trimmed string with at least 1 character.
   */
  description: string;

  /**
   * Current task workflow state.
   * Valid values: `todo`, `in-progress`, or `done`.
   */
  status: TaskStatus;

  /**
   * ISO 8601 timestamp marking when the task was created.
   * Valid range: any valid date-time string produced by `new Date().toISOString()`.
   */
  createdAt: string;

  /**
   * ISO 8601 timestamp marking the most recent task update.
   * Valid range: any valid date-time string produced by `new Date().toISOString()`.
   */
  updatedAt: string;
}

/**
 * Request payload used to create or update a task.
 */
export interface TaskInput {
  /**
   * Short task title supplied by the client.
   * Valid range: non-empty trimmed string with at least 1 character.
   */
  title: string;

  /**
   * Detailed task description supplied by the client.
   * Valid range: non-empty trimmed string with at least 1 character.
   */
  description: string;

  /**
   * Desired workflow state for the task.
   * Valid values: `todo`, `in-progress`, or `done`.
   */
  status: TaskStatus;
}
